title: Eirbot
logo: /assets/logo.png
description: >-
  Eirbot est l'association de robotique de l'ENSEIRB-MATMECA qui concourt chaque
  année à la coupe de france de robotique / Eurobot en concevant et réalisant
  plusieurs robots.
github_username: eirbot
show_downloads: false
google_analytics:
