# This site is built upon jekyll-theme-prologue
# See https://github.io/chrisbobbe/jekyll-theme-prologue for documentation


title: Eirbot
subtitle: ENSEIRB-MATMECA
description: >-
  Eirbot est l'association de robotique de l'ENSEIRB-MATMECA qui concourt chaque
  année à la coupe de france de robotique / Eurobot en concevant et réalisant
  plusieurs robots.
author: Eirbot
email: contact.eirbot@listes.enseirb-matmeca.fr
avatar: assets/images/eirbot_logo.svg

baseurl: ""
url: "https://eirbot.github.io"

twitter_url:
facebook_url: https://www.facebook.com/eirbot
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/eirbot
pinterest_url:
slack_url:
dribbble_url:

google_analytics:

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
